### ISSUE TITLE
Falcon Events App ID Reusability and Offset Management 

### ISSUE THREAD

**Issue by dylanraithel** [CrowdStrike/gofalcon#363] opened 2023-08-21 20:35 UTC
https://github.com/CrowdStrike/gofalcon/blob/aba61700b3b2ba8b456787dbcd11b5de58c483df/examples/falcon_event_stream/main.go#L61-L85

What's the correct way to reuse a stream over multiple lifecycles of an app? Do I need to generate a new app id for every run? Can I guarantee that an offset references the same data between app-id's? Meaning, if I were to generate a new unique app id for every run, would the previous run's offset be a useful value for the next run whose app-id is different?

**Comment by dylanraithel** [comment] 2023-08-21 20:36
@punkrokk fyi

**Comment by ffalor** [comment] 2023-08-22 16:21
Offset will reference the same event regardless of appid.

appid is a unique identifier for an open connection. You can reuse the same appid (as long as no one else is using it) or you can use a new one on each run.

**Comment by ffalor** [comment] 2023-08-25 17:06
Closing if you have more questions feel free to reopen or comment

**Comment by dylanraithel** [comment] 2023-09-01 19:56
Hi @ffalor thanks for the response. 

So on our side in the Falcon audit UI I'll see the stream start and stop for a given app id, then on the next run of our app the ListAvailableStreams api call returns zero streams for the app-id (that previously worked). When we make the same ListAvailableStreams call with a new unique app-id we get a MainAvailableStreamV2 back whose Response has a DataFeed url that correctly points to a url with our app id (and all the session token info we need to actually connect) If we re-use the same app id even after the stream stops on the falcon side we can't ever get an available stream back with the app-id again. I'd be inclined to cache the data feed url but because that struct has a bunch of other fields in it that relate to session tokens I'm hesitant to go down that path (probably fraught with peril)

**Comment by ffalor** [comment] 2023-09-01 21:41
Hey @dylanraithel 

If the `/sensors//entities/datafeed/v2` endpoint (`client.EventStreams.ListAvailableStreamsOAuth2`) returns null for a appid that means that appid is still in use. Once that connection is closed hitting the above endpoint with the same appid will then return a valid response.

You can test this out with the [example](https://github.com/CrowdStrike/gofalcon/blob/main/examples/falcon_event_stream/main.go) we have in this repo. Start it and then open a new terminal and start another. The second one should get this error: `No available stream was found. This may be caused by second instance of this application already running in your environment with ID=%s, or by missing streaming api capability`. Canceling the first one (CMD+C) and rerunning the second one should allow the second one to run successfully. This is what I just did to verify the expected functionality. 

LMK, if I misunderstood your issue/question.

**Comment by ffalor** [comment] 2023-09-01 22:06
@dylanraithel just did another test where I opened a stream and called `stream.Close()` and the appid wasn't released until the full program terminated. There may be a bug with the current package I will investigate.

**Comment by ffalor** [comment] 2023-09-06 17:18
Hey @dylanraithel I have a branch that fixes the main issue you saw where closing the stream doesn't actually close the connections. Would you be able to test the changes? This should allow you to open the stream, read events, and close the stream and reopen again. https://github.com/ffalor/gofalcon/tree/eventstream 

I'm not ready to merge yet because if we open and instantly close the connection the appid is unavailable for like 10 seconds even though there are no connections. I am trying to determine if that is our API doing this or if a code change can fix the issue.

**Comment by dylanraithel** [comment] 2023-09-06 18:45
Thanks for the fast turnaround @ffalor we'll test this out and get back to you ASAP

**Comment by punkrokk** [comment] 2023-09-06 18:50
@ffalor is this the [regen](https://github.com/CrowdStrike/gofalcon/tree/regen) branch?

**Comment by ffalor** [comment] 2023-09-06 20:03
@punkrokk no it was in my fork, but I went ahead and added it the CrowdStrike repo under the [eventstream](https://github.com/CrowdStrike/gofalcon/tree/eventstream) branch

**Comment by punkrokk** [comment] 2023-09-06 20:11
thanks @naz5617 found it

**Comment by naz5617** [comment] 2023-09-07 18:20
Hey, @ffalor I tested with your changes from the fork, I wasn't able to get this to change our current issue. I tested with just changing to the fork, I also tested with adding the 10 second delay into the end of our code so on our second iteration takes longer to start up based off of what you said. After these failed I removed defer from the `stream.Close()` and tested that with and without the 10 seconds. Currently our issue is persisting, where on any future iteration of running after the first, then on the next run of our app the ListAvailableStreams api call returns zero streams for the app-id (that previously worked).

**Comment by ffalor** [comment] 2023-09-07 18:23
@naz5617 the code I saw had the defer steam.Close() after at the end of the function. There were a few return statements between the stream creation and the defer statement. Those return statements look like they could happen before the defer statement is reached. Can you move the `defer stream.Close()` statement to the the right after creating the stream?

**Comment by naz5617** [comment] 2023-09-07 18:25
I'll test this out now.

**Comment by naz5617** [comment] 2023-09-07 18:37
This fixed this moving the `defer streamHandle.Close()` farther up in the code has led this to be fully functional from what I can tell from my testing, Thank you very much! We will be testing this more extensively, is there anything you need from us?

**Comment by ffalor** [comment] 2023-09-07 19:01
Great to hear! 

> I'm not ready to merge yet because if we open and instantly close the connection the appid is unavailable for like 10 seconds even though there are no connections. I am trying to determine if that is our API doing this or if a code change can fix the issue.

I believe the weird behavior I was seeing earlier where opening and closing the connection (instantly) would lock the appid is actually not caused by our code, but something that happens on the backend. I was able to confirm the lock is always removed after 1 minute in these situations. The above behavior doesn't happen if the stream is open for even ~1 second so it's not something you should run into. 

I'm going to try to reproduce in another language and if I can I'll merge and release a new version with the bug fixes for `.Close()`

**Comment by ffalor** [comment] 2023-09-07 20:47
I wasn't able to reproduce in Python, but I was able to reproduce in Rust. I don't think python is fast enough. This should put into perspective how fast the cancel must happen in order to hit the 1-minute lockout period the backend does.

I will work on getting the release out today it should be `v0.4.2`

**Closed** 2023-09-08 13:42 UTC
Labels: bug

**Comment by ffalor** [comment] 2023-09-08 14:12
v0.4.2 released & contains this fix. Thank you for reporting the issue
